name: Back Continuous Integration

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: ğŸ‘® Lint & Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ğŸ¥Ÿ Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.9'
      - name: ğŸ”“ Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - run: bun install --cwd back
      - run: bun --cwd back biome ci
      - run: bun --cwd back tsc

  test-unit:
    name: ğŸ‡ Test Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ğŸ¥Ÿ Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.9'
      - name: ğŸ”“ Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - run: bun install --cwd back
      - run: bun --cwd back test:unit

  test-int:
    name: ğŸ¢ Test Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ğŸ¥Ÿ Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.9'
      - name: ğŸ”“ Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - run: bun install --cwd back
      - run: bun --cwd back test:int

  test-feat:
    name: ğŸŒ Test Feature
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOOLS: true
    steps:
      - uses: actions/checkout@v4
      - name: ğŸ¥Ÿ Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.9'
      - name: ğŸ”“ Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - run: bun install --cwd back
      - run: bun --cwd back test:feat


